cinema = {
    "A": [
        {"seat": "1", "booked": False},
        {"seat": "2", "booked": False},
        {"seat": "3", "booked": False},
        {"seat": "4", "booked": False},
        {"seat": "5", "booked": False},
        {"seat": "6", "booked": False},
        {"seat": "7", "booked": False},
        {"seat": "8", "booked": False},
        {"seat": "9", "booked": False},
        {"seat": "10", "booked": False},
        {"seat": "11", "booked": False},
        {"seat": "12", "booked": False},
        {"seat": "13", "booked": False}
    ],
    "B": [
        {"seat": "1", "booked": False},
        {"seat": "2", "booked": False},
        {"seat": "3", "booked": False},
        {"seat": "4", "booked": False},
        {"seat": "5", "booked": False},
        {"seat": "6", "booked": False},
        {"seat": "7", "booked": False},
        {"seat": "8", "booked": False},
        {"seat": "9", "booked": False},
        {"seat": "10", "booked": False},
        {"seat": "11", "booked": False},
        {"seat": "12", "booked": False},
        {"seat": "13", "booked": False}
    ],
    "C": [
        {"seat": "1", "booked": False},
        {"seat": "2", "booked": False},
        {"seat": "3", "booked": False},
        {"seat": "4", "booked": False},
        {"seat": "5", "booked": False},
        {"seat": "6", "booked": False},
        {"seat": "7", "booked": False},
        {"seat": "8", "booked": False},
        {"seat": "9", "booked": False},
        {"seat": "10", "booked": False},
        {"seat": "11", "booked": False},
        {"seat": "12", "booked": False},
        {"seat": "13", "booked": False}
    ],
    "D": [
        {"seat": "1", "booked": False},
        {"seat": "2", "booked": False},
        {"seat": "3", "booked": False},
        {"seat": "4", "booked": False},
        {"seat": "5", "booked": False},
        {"seat": "6", "booked": True},
        {"seat": "7", "booked": True},
        {"seat": "8", "booked": True},
        {"seat": "9", "booked": True},
        {"seat": "10", "booked": True},
        {"seat": "11", "booked": True},
        {"seat": "12", "booked": False},
        {"seat": "13", "booked": False}
    ],
    "E": [
        {"seat": "1", "booked": True},
        {"seat": "2", "booked": True},
        {"seat": "3", "booked": True},
        {"seat": "4", "booked": True},
        {"seat": "5", "booked": True},
        {"seat": "6", "booked": True},
        {"seat": "7", "booked": True},
        {"seat": "8", "booked": True},
        {"seat": "9", "booked": True},
        {"seat": "10", "booked": True},
        {"seat": "11", "booked": True}
    ],
    "F": [
        {"seat": "H1", "booked": False},
        {"seat": "H2", "booked": False},
        {"seat": "3", "booked": False},
        {"seat": "4", "booked": True},
        {"seat": "5", "booked": True},
        {"seat": "6", "booked": False},
        {"seat": "7", "booked": False},
        {"seat": "8", "booked": False},
        {"seat": "9", "booked": False},
        {"seat": "10", "booked": False},
        {"seat": "11", "booked": True},
        {"seat": "12", "booked": True},
       {"seat": "13", "booked": True},
       {"seat": "14", "booked": True}
    ]
}